export const SET_SELECT_TOPIC = "SET_SELECT_TOPIC";
export const SET_SELECT_TIME_PERIOD = "SET_SELECT_TIME_PERIOD";
export const SET_MODAL_OPEN = "SET_MODAL_OPEN";
export const SET_MODAL_DATA_PROPERTY = "SET_MODAL_DATA_PROPERTY";
export const SET_MODAL_TIME_PERIOD_TYPE = "SET_MODAL_TIME_PERIOD_TYPE";
